#!/usr/bin/env python3
"""
Phase-1 : Scraper Executor  (Standalone)
==========================================

What does this script do?
-------------------------
It takes a scraper file (generated by generator.py or written by hand)
and runs it safely in a sandboxed subprocess. Think of it as a "test
bench" for scrapers — it runs the code, captures everything that
happens, and tells you exactly what went right or wrong.

The scraper never touches your real system. It runs in an isolated
subprocess with:
  - A temporary working directory (deleted after the run)
  - A memory cap (default 512 MB)
  - A wall-clock timeout (default 60 seconds)
  - A stripped-down environment (no access to your env vars, home dir, etc.)

Before running, we also do a static safety check (validator) to catch
dangerous code patterns (eval, exec, subprocess, etc.) BEFORE they
ever execute.

Three things this file does
----------------------------
1. VALIDATE  – Parse the scraper code and check for forbidden imports or
               function calls (e.g. subprocess, eval, exec, os.system).
               This is a fast AST-based check, no code is actually run.

2. EXECUTE   – Run the scraper in a sandboxed subprocess against a given
               URL and collect the results.

3. FULL RUN  – Validate first, then execute if safe. This is the default.

Usage
-----
    # Run a scraper (validates first, then executes):
    python executor.py run scraper_example_com.py "https://example.com/tenders"

    # Just validate (no execution):
    python executor.py validate scraper_example_com.py

    # Execute without validation (skip safety checks — use carefully!):
    python executor.py execute scraper_example_com.py "https://example.com/tenders"

    # Keep downloaded files in a specific directory:
    python executor.py run scraper.py "https://example.com" --keep-downloads ./results

Environment Variables (optional, set in shell or .env):
    SANDBOX_TIMEOUT    – max seconds for scraper to run (default: 60)
    SANDBOX_MEMORY_MB  – max memory in MB (default: 512)
    LOG_LEVEL          – logging verbosity (default: INFO)

No project imports. No external dependencies. Just Python 3.10+ stdlib.
"""
from __future__ import annotations

import argparse
import ast
import json
import logging
import os
import platform
import signal
import shutil
import subprocess
import sys
import tempfile
import time
from dataclasses import dataclass, field
from pathlib import Path
from textwrap import dedent

# `resource` is Unix-only — we import it conditionally so the script
# runs on Windows too (just without memory caps).
try:
    import resource  # type: ignore[import-not-found]
except ImportError:
    resource = None  # type: ignore[assignment]

IS_WINDOWS = platform.system() == "Windows"


# ═══════════════════════════════════════════════════════════════════════════════
#  SECTION 0 :  Configuration
# ═══════════════════════════════════════════════════════════════════════════════
# .env loading approach — keeps things consistent
# ═══════════════════════════════════════════════════════════════════════════════

def _load_dotenv():
    """
    Dead-simple .env file reader (no external dependencies).

    Looks for a file called `.env` next to this script or in the current
    working directory. Each line should look like:

        SANDBOX_TIMEOUT=120
        SANDBOX_MEMORY_MB=1024

    Lines starting with '#' are comments.
    Real env vars always take priority over .env values.
    """
    possible_locations = [
        Path(__file__).parent / ".env",  # same folder as executor.py
        Path.cwd() / ".env",            # wherever you ran the command from
    ]
    # Also walk up from the script's directory to find a project-root .env
    # (e.g. when this file lives in UNi/Phase-1/ but .env is at the repo root)
    parent = Path(__file__).parent.parent
    for _ in range(5):  # max 5 levels up to avoid scanning the whole filesystem
        candidate = parent / ".env"
        if candidate.is_file() and candidate not in possible_locations:
            possible_locations.append(candidate)
        if parent == parent.parent:
            break
        parent = parent.parent
    for env_file in possible_locations:
        if env_file.is_file():
            for line in env_file.read_text().splitlines():
                line = line.strip()
                if not line or line.startswith("#") or "=" not in line:
                    continue
                key, _, value = line.partition("=")
                key = key.strip()
                value = value.strip().strip("\"'")
                os.environ.setdefault(key, value)
            break


# Load .env right away
_load_dotenv()

# --- Configurable settings ---
SANDBOX_TIMEOUT   = int(os.getenv("SANDBOX_TIMEOUT", "60"))       # seconds
SANDBOX_MEMORY_MB = int(os.getenv("SANDBOX_MEMORY_MB", "512"))    # megabytes
LOG_LEVEL         = os.getenv("LOG_LEVEL", "INFO").upper()

# Set up logging
logging.basicConfig(
    format="%(asctime)s  %(levelname)-8s  %(message)s",
    level=getattr(logging, LOG_LEVEL, logging.INFO),
)
log = logging.getLogger("phase1.executor")


# ═══════════════════════════════════════════════════════════════════════════════
#  SECTION 1 :  Validator  (re-exported from validator.py)
# ═══════════════════════════════════════════════════════════════════════════════
# Per ARCHITECTURE.md the static-safety check lives in its own module
# (`validator.py`). We re-export the public API here so existing code that
# does `from executor import validate` keeps working unchanged.
# ═══════════════════════════════════════════════════════════════════════════════

from validator import (  # noqa: E402  (import after stdlib block, intentional)
    FORBIDDEN_IMPORTS,
    FORBIDDEN_CALLS,
    REQUIRED_FUNCTION,
    ValidationResult,
    validate,
    _resolve_call_name,  # re-exported for backward compat with test_validator.py
)


# ═══════════════════════════════════════════════════════════════════════════════
#  SECTION 2 :  Sandbox  (Safe Subprocess Runner)
# ═══════════════════════════════════════════════════════════════════════════════
# The sandbox runs a Python script in a completely isolated subprocess.
# It's the second line of defense (after the validator).
#
# What does "isolated" mean here?
#   - The subprocess runs in a temporary directory (not your project folder)
#   - Environment variables are stripped to a bare minimum
#   - Memory is capped (default: 512 MB) using resource.setrlimit on
#     Unix, or via Windows Job Objects where available
#   - Wall-clock time is capped (default: 60 seconds)
#   - Core dumps are disabled (Unix only)
#   - The process runs in its own process group (so we can kill the
#     whole tree if it spawns children)
#
# Cross-platform notes:
#   - resource.setrlimit / os.setsid / os.killpg are Unix-only.
#     On Windows we use CREATE_NEW_PROCESS_GROUP and taskkill.
#   - The PATH env var is built dynamically per platform.
#
# If the scraper crashes, hangs, or runs out of memory, the sandbox
# catches it cleanly and reports what happened.
#
# NOTE: This is the Python-level sandbox. For production, you'd also want
#       container-level isolation (Docker, gVisor, Firecracker, etc.).
# ═══════════════════════════════════════════════════════════════════════════════

@dataclass
class SandboxResult:
    """
    What comes back from running a script in the sandbox.

    returncode:  the subprocess exit code (0 = success, non-zero = error)
    stdout:      everything the script printed to stdout
    stderr:      everything the script printed to stderr
    elapsed:     how many seconds the script ran
    timed_out:   True if we had to kill the script because it ran too long
    """
    returncode: int
    stdout: str
    stderr: str
    elapsed: float
    timed_out: bool = False


def _build_preexec_fn(memory_mb: int):
    """
    Create a function that runs BEFORE the subprocess starts (Unix only).

    This is where we set the resource limits. It runs inside the child
    process, so the limits only affect the scraper — not our main script.

    We set:
    - RLIMIT_AS:   cap address space (total memory the process can allocate)
    - RLIMIT_CORE: disable core dumps (we don't need crash dumps)
    - os.setsid():  put the process in a new session group so we can
                    kill it and all its children with one signal

    On Windows this returns None — preexec_fn is not supported there.
    Windows sandboxing uses CREATE_NEW_PROCESS_GROUP instead.
    """
    if IS_WINDOWS:
        return None  # preexec_fn is not available on Windows

    def _apply():
        # Cap memory
        if resource is not None:
            try:
                bytes_cap = memory_mb * 1024 * 1024
                resource.setrlimit(resource.RLIMIT_AS, (bytes_cap, bytes_cap))
            except Exception:
                pass  # Some systems don't support RLIMIT_AS — that's okay

            # Disable core dumps
            try:
                resource.setrlimit(resource.RLIMIT_CORE, (0, 0))
            except Exception:
                pass

        # New process group (so we can kill the entire tree later)
        os.setsid()

    return _apply


def _kill_process_tree(proc: subprocess.Popen):
    """
    Kill a subprocess and all its children.

    On Unix:    kill the process group via os.killpg (SIGKILL).
    On Windows: use taskkill /T /F to terminate the tree.
    """
    try:
        if IS_WINDOWS:
            # /T = kill child processes,  /F = force,  /PID = target process
            subprocess.call(
                ["taskkill", "/T", "/F", "/PID", str(proc.pid)],
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
        else:
            os.killpg(proc.pid, signal.SIGKILL)
    except Exception:
        # Fallback: just kill the main process
        proc.kill()


def run_in_sandbox(
    script_path: str,
    workdir: str,
    timeout: int = SANDBOX_TIMEOUT,
    memory_mb: int = SANDBOX_MEMORY_MB,
) -> SandboxResult:
    """
    Run a Python script in a locked-down subprocess.

    The script runs with:
    - A forced working directory
    - A minimal environment (no access to your real env vars)
    - Memory and wall-clock caps
    - Stdout and stderr captured for analysis

    If the script exceeds the timeout, we kill the entire process group
    and return a result with timed_out=True.
    """

    # Minimal environment — the scraper only gets what it absolutely needs.
    # No API keys, no database URLs, no home directory access.
    if IS_WINDOWS:
        env = {
            "PATH": os.environ.get("PATH", ""),  # Windows needs its real PATH for python.exe
            "SYSTEMROOT": os.environ.get("SYSTEMROOT", r"C:\Windows"),
            "PYTHONPATH": workdir,
            "USERPROFILE": workdir,  # Windows "home" equivalent
            "TEMP": workdir,
            "TMP": workdir,
        }
    else:
        env = {
            "PATH": "/usr/local/bin:/usr/bin:/bin",
            "PYTHONPATH": workdir,      # so it can import its own modules
            "HOME": workdir,            # fake home directory
            "TMPDIR": workdir,          # temp files go in the sandbox
            "LC_ALL": "C.UTF-8",       # consistent encoding
            "LANG": "C.UTF-8",
        }

    t0 = time.time()

    # --- Spawn the subprocess ---
    # On Windows we use CREATE_NEW_PROCESS_GROUP so we can terminate the
    # entire tree later via taskkill.  On Unix we rely on preexec_fn to
    # call os.setsid() for the same purpose.
    popen_kwargs: dict = {
        "cwd": workdir,
        "env": env,
        "stdout": subprocess.PIPE,
        "stderr": subprocess.PIPE,
    }
    preexec = _build_preexec_fn(memory_mb)
    if preexec is not None:
        popen_kwargs["preexec_fn"] = preexec
    if IS_WINDOWS:
        popen_kwargs["creationflags"] = subprocess.CREATE_NEW_PROCESS_GROUP

    try:
        proc = subprocess.Popen(
            [sys.executable, script_path],    # same Python interpreter as us
            **popen_kwargs,
        )
    except Exception as e:
        return SandboxResult(
            returncode=-1,
            stdout="",
            stderr=f"Failed to start sandbox subprocess: {e}",
            elapsed=0.0,
        )

    # --- Wait for it to finish (or kill it if it takes too long) ---
    try:
        stdout_bytes, stderr_bytes = proc.communicate(timeout=timeout)
        return SandboxResult(
            returncode=proc.returncode,
            stdout=stdout_bytes.decode("utf-8", errors="replace"),
            stderr=stderr_bytes.decode("utf-8", errors="replace"),
            elapsed=time.time() - t0,
        )
    except subprocess.TimeoutExpired:
        # The scraper took too long — kill the entire process group
        log.warning("Scraper timed out after %d seconds — killing process", timeout)
        _kill_process_tree(proc)
        stdout_bytes, stderr_bytes = proc.communicate()
        return SandboxResult(
            returncode=-9,
            stdout=stdout_bytes.decode("utf-8", errors="replace"),
            stderr=stderr_bytes.decode("utf-8", errors="replace"),
            elapsed=time.time() - t0,
            timed_out=True,
        )


# ═══════════════════════════════════════════════════════════════════════════════
#  SECTION 3 :  Executor  (Ties Sandbox + Results Together)
# ═══════════════════════════════════════════════════════════════════════════════
# The executor is the high-level function your code should call.
# It handles the full workflow:
#
#   1. Create a temporary directory
#   2. Write the scraper code as "scraper.py" inside it
#   3. Write a small "runner" script that imports scrape() and calls it
#   4. Run the runner in the sandbox
#   5. Read the results (what files were downloaded, any errors, etc.)
#   6. Clean up the temp directory
#
# The reason we have a separate "runner" script (instead of running
# scraper.py directly) is so we can:
#   - Catch exceptions and write them to a JSON file
#   - Measure elapsed time
#   - Capture the return value (list of downloaded files)
#
# The scraper itself just needs to define:
#   def scrape(url: str, output_dir: str) -> dict | list
# ═══════════════════════════════════════════════════════════════════════════════

@dataclass
class ExecutionResult:
    """
    The final result of executing a scraper.

    success:           did the scraper run without errors AND produce output?
    downloaded_files:  list of file paths the scraper saved
    scraper_output:    whatever the scrape() function returned (could be dict or list)
    stdout:            everything the scraper printed to stdout
    stderr:            everything the scraper printed to stderr
    runtime_seconds:   how long the scraper ran
    timed_out:         True if the scraper was killed for exceeding the time limit
    error:             error message if something went wrong (None if ok)
    """
    success: bool
    downloaded_files: list[str] = field(default_factory=list)
    scraper_output: dict | list | None = None
    stdout: str = ""
    stderr: str = ""
    runtime_seconds: float = 0.0
    timed_out: bool = False
    error: str | None = None


# This is the small "runner" script we inject into the temp directory.
# It imports the scraper, calls scrape(), and writes the result to a
# JSON file that we read back afterwards.
#
# Why not run scraper.py directly? Because we need to:
#   - Catch any exceptions the scraper throws
#   - Record the return value
#   - Measure how long it took
#
# The double-braces {{}} are because this is a .format() template —
# Python's format() uses {} for placeholders, so we escape literal
# braces by doubling them.
_RUNNER_SCRIPT = '''\
import json
import sys
import traceback
import time

# Make sure we can import the scraper from the working directory
sys.path.insert(0, {workdir!r})
from scraper import scrape

t0 = time.time()
try:
    # Call the scraper's main function
    output = scrape({url!r}, {output_dir!r})

    # Handle both return types:
    #   - dict  (new format: {{"tenders": [...], "downloaded_files": [...]}})
    #   - list  (old format: list of file paths)
    if isinstance(output, dict):
        result = {{
            "ok": True,
            "output": output,
            "files": output.get("downloaded_files", []),
            "elapsed": time.time() - t0,
        }}
    else:
        # Legacy format: scrape() returned a list of paths
        result = {{
            "ok": True,
            "output": output,
            "files": output if isinstance(output, list) else [],
            "elapsed": time.time() - t0,
        }}

except Exception as e:
    result = {{
        "ok": False,
        "error": str(e),
        "traceback": traceback.format_exc(),
        "elapsed": time.time() - t0,
    }}

# Write the result to a JSON file so the executor can read it back
with open({result_path!r}, "w") as f:
    json.dump(result, f, default=str)
'''


def execute(code: str, url: str, keep_downloads: str | None = None) -> ExecutionResult:
    """
    Execute a scraper in the sandbox and return the results.

    Args:
        code:            the Python source code of the scraper
        url:             the target URL to pass to scrape()
        keep_downloads:  if set, copy downloaded files here instead of
                         letting them be deleted with the temp directory

    Returns:
        ExecutionResult with success status, downloaded files, output, errors, etc.
    """

    with tempfile.TemporaryDirectory(prefix="phase1-run-") as workdir:
        work = Path(workdir)

        # Create a "downloads" subfolder — this is where the scraper saves files
        output_dir = work / "downloads"
        output_dir.mkdir()

        # Write the scraper code as scraper.py
        scraper_file = work / "scraper.py"
        scraper_file.write_text(code)

        # The runner will write its result here
        result_path = work / "result.json"

        # Generate the runner script with all paths filled in
        runner_code = _RUNNER_SCRIPT.format(
            workdir=str(work),
            url=url,
            output_dir=str(output_dir),
            result_path=str(result_path),
        )
        runner_path = work / "_runner.py"
        runner_path.write_text(runner_code)

        # --- Run it in the sandbox ---
        log.info("Starting sandbox execution (timeout=%ds, memory=%dMB)",
                 SANDBOX_TIMEOUT, SANDBOX_MEMORY_MB)
        sandbox = run_in_sandbox(
            script_path=str(runner_path),
            workdir=str(work),
            timeout=SANDBOX_TIMEOUT,
            memory_mb=SANDBOX_MEMORY_MB,
        )

        # --- Check if the runner even produced a result file ---
        # If result.json doesn't exist, the scraper probably crashed hard
        # (segfault, out of memory, killed by timeout, etc.)
        if not result_path.exists():
            return ExecutionResult(
                success=False,
                stdout=sandbox.stdout,
                stderr=sandbox.stderr,
                runtime_seconds=sandbox.elapsed,
                timed_out=sandbox.timed_out,
                error=(
                    "Scraper crashed without producing a result. "
                    "Likely cause: timeout, out of memory, or segfault."
                    + (" [TIMED OUT]" if sandbox.timed_out else "")
                ),
            )

        # --- Parse the result file ---
        try:
            payload = json.loads(result_path.read_text())
        except Exception as e:
            return ExecutionResult(
                success=False,
                stderr=sandbox.stderr,
                runtime_seconds=sandbox.elapsed,
                error=f"Runner produced invalid result.json: {e}",
            )

        # --- Did the scraper itself fail? ---
        if not payload.get("ok"):
            return ExecutionResult(
                success=False,
                stdout=sandbox.stdout,
                stderr=sandbox.stderr,
                runtime_seconds=payload.get("elapsed", sandbox.elapsed),
                error=payload.get("error") or "Unknown scraper error",
            )

        # --- Collect downloaded files ---
        # The runner reports which files scrape() said it downloaded.
        # We verify each one actually exists on disk.
        downloaded = []
        for filepath in payload.get("files", []):
            if os.path.isfile(filepath):
                downloaded.append(filepath)

        # Also check for any files in the downloads directory that the
        # scraper might have created but not reported in its return value
        for extra_file in output_dir.rglob("*"):
            if extra_file.is_file() and str(extra_file) not in downloaded:
                downloaded.append(str(extra_file))

        # --- Optionally copy downloads to a persistent location ---
        if keep_downloads and downloaded:
            keep_dir = Path(keep_downloads)
            keep_dir.mkdir(parents=True, exist_ok=True)
            saved_copies = []
            for filepath in downloaded:
                src = Path(filepath)
                dst = keep_dir / src.name
                # Handle filename collisions by adding a number
                if dst.exists():
                    stem, suffix = dst.stem, dst.suffix
                    counter = 1
                    while dst.exists():
                        dst = keep_dir / f"{stem}_{counter}{suffix}"
                        counter += 1
                shutil.copy2(str(src), str(dst))
                saved_copies.append(str(dst))
                log.info("Saved: %s", dst)
            downloaded = saved_copies

        return ExecutionResult(
            success=True,
            downloaded_files=downloaded,
            scraper_output=payload.get("output"),
            stdout=sandbox.stdout,
            stderr=sandbox.stderr,
            runtime_seconds=payload.get("elapsed", sandbox.elapsed),
        )


# ═══════════════════════════════════════════════════════════════════════════════
#  SECTION 4 :  CLI  (Command-Line Interface)
# ═══════════════════════════════════════════════════════════════════════════════
# So your friend can run this directly from the terminal.
#
#   python executor.py run scraper.py "https://example.com/tenders"
#   python executor.py validate scraper.py
#   python executor.py execute scraper.py "https://example.com/tenders"
# ═══════════════════════════════════════════════════════════════════════════════

def _print_validation_result(val: ValidationResult):
    """Pretty-print the validation result."""
    if val.ok:
        print("✅ Validation PASSED — no safety issues found.\n")
    else:
        print("❌ Validation FAILED — the following issues were found:\n")
        for err in val.errors:
            print(f"   ✖ {err}")
        print()
    if val.warnings:
        print("⚠  Warnings:")
        for warn in val.warnings:
            print(f"   • {warn}")
        print()


def _print_execution_result(result: ExecutionResult):
    """Pretty-print the execution result."""
    print(f"\n{'═'*60}")
    print(f"  Status:     {'✅ SUCCESS' if result.success else '❌ FAILED'}")
    print(f"  Runtime:    {result.runtime_seconds:.1f}s")
    if result.timed_out:
        print(f"  ⚠ TIMED OUT after {SANDBOX_TIMEOUT}s")
    print(f"  Files:      {len(result.downloaded_files)} downloaded")

    if result.error:
        print(f"  Error:      {result.error}")

    if result.downloaded_files:
        print(f"\n  Downloaded files:")
        for f in result.downloaded_files:
            size = os.path.getsize(f) if os.path.exists(f) else 0
            size_str = f"{size / 1024:.1f} KB" if size < 1_000_000 else f"{size / 1_000_000:.1f} MB"
            print(f"    📄 {Path(f).name}  ({size_str})")

    if result.scraper_output and isinstance(result.scraper_output, dict):
        tenders = result.scraper_output.get("tenders", [])
        if tenders:
            print(f"\n  Scraped tenders: {len(tenders)}")
            for i, t in enumerate(tenders[:5], 1):  # show first 5
                title = t.get("title", "untitled")
                print(f"    {i}. {title}")
            if len(tenders) > 5:
                print(f"    ... and {len(tenders) - 5} more")

    print(f"{'═'*60}\n")

    # Show stdout/stderr if there's something interesting
    if result.stdout.strip():
        print("── stdout ──")
        print(result.stdout[:3000])
        if len(result.stdout) > 3000:
            print(f"... ({len(result.stdout)} chars total, truncated)")
        print()

    if result.stderr.strip():
        print("── stderr ──")
        print(result.stderr[:3000])
        if len(result.stderr) > 3000:
            print(f"... ({len(result.stderr)} chars total, truncated)")
        print()


def cmd_validate(args: argparse.Namespace):
    """Just validate the scraper code — don't run it."""
    code = Path(args.file).read_text()
    log.info("Validating: %s", args.file)

    result = validate(code)
    _print_validation_result(result)

    # Exit with non-zero status if validation failed
    sys.exit(0 if result.ok else 1)


def cmd_execute(args: argparse.Namespace):
    """Execute the scraper in sandbox — skip validation."""
    code = Path(args.file).read_text()
    log.info("Executing: %s against %s (no validation)", args.file, args.url)

    result = execute(code, args.url, keep_downloads=args.keep_downloads)
    _print_execution_result(result)

    sys.exit(0 if result.success else 1)


def cmd_run(args: argparse.Namespace):
    """Validate first, then execute if safe. This is the recommended command."""
    code = Path(args.file).read_text()

    # Step 1: Validate
    log.info("Step 1/2: Validating %s ...", args.file)
    val = validate(code)
    _print_validation_result(val)

    if not val.ok:
        print("❌ Aborting — scraper code failed safety checks.")
        print("   Fix the issues above, or use `execute` to skip validation.\n")
        sys.exit(1)

    # Step 2: Execute
    log.info("Step 2/2: Executing %s against %s ...", args.file, args.url)
    result = execute(code, args.url, keep_downloads=args.keep_downloads)
    _print_execution_result(result)

    sys.exit(0 if result.success else 1)


def main():
    """Parse command-line arguments and run the appropriate command."""

    parser = argparse.ArgumentParser(
        description="Phase-1 Scraper Executor — Standalone",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=dedent("""\
            Examples:

              # Validate + run a scraper (recommended):
              python executor.py run scraper.py "https://example.com/tenders"

              # Just check if a scraper is safe to run:
              python executor.py validate scraper.py

              # Run without validation (use with caution):
              python executor.py execute scraper.py "https://example.com"

              # Keep downloaded files:
              python executor.py run scraper.py "https://example.com" --keep-downloads ./results
        """),
    )
    subcommands = parser.add_subparsers(dest="command", required=True)

    # ── "validate" — safety check only ────────────────────────────────
    p_val = subcommands.add_parser(
        "validate",
        help="Check scraper code for safety issues (no execution)",
    )
    p_val.add_argument("file",
                       help="Path to the scraper .py file")

    # ── "execute" — sandbox only (no validation) ──────────────────────
    p_exe = subcommands.add_parser(
        "execute",
        help="Execute scraper in sandbox (skips validation)",
    )
    p_exe.add_argument("file",
                       help="Path to the scraper .py file")
    p_exe.add_argument("url",
                       help="Target URL to pass to scrape()")
    p_exe.add_argument("--keep-downloads", "-k", default=None,
                       help="Directory to copy downloaded files to (default: deleted with temp dir)")

    # ── "run" — validate + execute (recommended) ─────────────────────
    p_run = subcommands.add_parser(
        "run",
        help="Validate then execute (recommended — safest option)",
    )
    p_run.add_argument("file",
                       help="Path to the scraper .py file")
    p_run.add_argument("url",
                       help="Target URL to pass to scrape()")
    p_run.add_argument("--keep-downloads", "-k", default=None,
                       help="Directory to copy downloaded files to (default: deleted with temp dir)")

    # ── Dispatch ──────────────────────────────────────────────────────
    args = parser.parse_args()

    commands = {
        "validate": cmd_validate,
        "execute":  cmd_execute,
        "run":      cmd_run,
    }
    commands[args.command](args)


# ─── Entry point ──────────────────────────────────────────────────────────────
if __name__ == "__main__":
    main()
