"""
Master procurement-portal directory — the 100 domains from the project's source
publications workbook (docs/publications_28_05_2026.xlsx).

Generated, checked-in data (the workbook is not shipped in the backend image).
The public tender directory lists every portal here so users can jump to the
official site, and overlays a live open-tender count for any domain we've scraped.
Regenerate by re-running the one-off extractor over the workbook.
"""
from __future__ import annotations

# (domain, official_site_url)
PORTAL_DOMAINS: list[dict[str, str]] = [
    {"domain": 'ausschreibung.halle.de', "site_url": 'https://ausschreibung.halle.de'},
    {"domain": 'ausschreibungen.giz.de', "site_url": 'https://ausschreibungen.giz.de'},
    {"domain": 'ausschreibungen.kfw.de', "site_url": 'https://ausschreibungen.kfw.de'},
    {"domain": 'ausschreibungen.landbw.de', "site_url": 'https://ausschreibungen.landbw.de'},
    {"domain": 'ausschreibungen.mainpost.de', "site_url": 'https://ausschreibungen.mainpost.de'},
    {"domain": 'beschaffungen.barmer.de', "site_url": 'https://beschaffungen.barmer.de'},
    {"domain": 'bi-medien.de', "site_url": 'https://bi-medien.de'},
    {"domain": 'bieter.ehealth-evergabe.de', "site_url": 'https://bieter.ehealth-evergabe.de'},
    {"domain": 'bieterportal.dfg.e-va.eu', "site_url": 'https://bieterportal.dfg.e-va.eu'},
    {"domain": 'bieterportal.noncd.db.de', "site_url": 'https://bieterportal.noncd.db.de'},
    {"domain": 'bieterportal.pd-g.e-va.eu', "site_url": 'https://bieterportal.pd-g.e-va.eu'},
    {"domain": 'bieterzugang.deutsche-evergabe.de', "site_url": 'https://bieterzugang.deutsche-evergabe.de'},
    {"domain": 'bund.vergabe24.de', "site_url": 'https://bund.vergabe24.de'},
    {"domain": 'deutsche-rentenversicherung-bund.de', "site_url": 'https://deutsche-rentenversicherung-bund.de'},
    {"domain": 'eit-culture-creativity.eu', "site_url": 'https://eit-culture-creativity.eu'},
    {"domain": 'eliagroup.sharepoint.com', "site_url": 'https://eliagroup.sharepoint.com'},
    {"domain": 'eom-vp-prod.ai-hosting.de', "site_url": 'https://eom-vp-prod.ai-hosting.de'},
    {"domain": 'eu.mu.ariba.com', "site_url": 'https://eu.mu.ariba.com'},
    {"domain": 'evergabe-mv.de', "site_url": 'https://evergabe-mv.de'},
    {"domain": 'evergabe.blb.nrw.de', "site_url": 'https://evergabe.blb.nrw.de'},
    {"domain": 'fbhh-evergabe.web.hamburg.de', "site_url": 'https://fbhh-evergabe.web.hamburg.de'},
    {"domain": 'ffb.healyhudson.biz', "site_url": 'https://ffb.healyhudson.biz'},
    {"domain": 'fham-vp-prod.ai-hosting.de', "site_url": 'https://fham-vp-prod.ai-hosting.de'},
    {"domain": 'it-vergabe.eu', "site_url": 'https://it-vergabe.eu'},
    {"domain": 'landesverwaltung.vergabe.rlp.de', "site_url": 'https://landesverwaltung.vergabe.rlp.de'},
    {"domain": 'lbb.vergabe.rlp.de', "site_url": 'https://lbb.vergabe.rlp.de'},
    {"domain": 'lbm.vergabe.rlp.de', "site_url": 'https://lbm.vergabe.rlp.de'},
    {"domain": 'lhs-vpbw.vmstart.de', "site_url": 'https://lhs-vpbw.vmstart.de'},
    {"domain": 'lwl.org', "site_url": 'https://lwl.org'},
    {"domain": 'meinauftrag.rib.de', "site_url": 'https://meinauftrag.rib.de'},
    {"domain": 'mp.aumass.de', "site_url": 'https://mp.aumass.de'},
    {"domain": 'plattform.aumass.de', "site_url": 'https://plattform.aumass.de'},
    {"domain": 'pnp.aumass.de', "site_url": 'https://pnp.aumass.de'},
    {"domain": 'rlp.vergabekommunal.de', "site_url": 'https://rlp.vergabekommunal.de'},
    {"domain": 'saarvpsl.vmstart.de', "site_url": 'https://saarvpsl.vmstart.de'},
    {"domain": 'satellite.dtvp.de', "site_url": 'https://satellite.dtvp.de'},
    {"domain": 'trading.energie-handelsplatz.de', "site_url": 'https://trading.energie-handelsplatz.de'},
    {"domain": 'vergabe.autobahn.de', "site_url": 'https://vergabe.autobahn.de'},
    {"domain": 'vergabe.bremen.de', "site_url": 'https://vergabe.bremen.de'},
    {"domain": 'vergabe.brw-haan.de', "site_url": 'https://vergabe.brw-haan.de'},
    {"domain": 'vergabe.bwbm.de', "site_url": 'https://vergabe.bwbm.de'},
    {"domain": 'vergabe.deges.de', "site_url": 'https://vergabe.deges.de'},
    {"domain": 'vergabe.duesseldorf.de', "site_url": 'https://vergabe.duesseldorf.de'},
    {"domain": 'vergabe.fraunhofer.de', "site_url": 'https://vergabe.fraunhofer.de'},
    {"domain": 'vergabe.hamburgwasser.de', "site_url": 'https://vergabe.hamburgwasser.de'},
    {"domain": 'vergabe.hessen.de', "site_url": 'https://vergabe.hessen.de'},
    {"domain": 'vergabe.hilgmbh.de', "site_url": 'https://vergabe.hilgmbh.de'},
    {"domain": 'vergabe.ihk.de', "site_url": 'https://vergabe.ihk.de'},
    {"domain": 'vergabe.landbw.de', "site_url": 'https://vergabe.landbw.de'},
    {"domain": 'vergabe.lvr.de', "site_url": 'https://vergabe.lvr.de'},
    {"domain": 'vergabe.muenchen.de', "site_url": 'https://vergabe.muenchen.de'},
    {"domain": 'vergabe.niedersachsen.de', "site_url": 'https://vergabe.niedersachsen.de'},
    {"domain": 'vergabe.stadt-frankfurt.de', "site_url": 'https://vergabe.stadt-frankfurt.de'},
    {"domain": 'vergabe.stadt-koeln.de', "site_url": 'https://vergabe.stadt-koeln.de'},
    {"domain": 'vergabe.tk.de', "site_url": 'https://vergabe.tk.de'},
    {"domain": 'vergabe.vmstart.de', "site_url": 'https://vergabe.vmstart.de'},
    {"domain": 'vergabemarktplatz.brandenburg.de', "site_url": 'https://vergabemarktplatz.brandenburg.de'},
    {"domain": 'vergabeplattform.bwi.de', "site_url": 'https://vergabeplattform.bwi.de'},
    {"domain": 'vergabeplattform.charite.de', "site_url": 'https://vergabeplattform.charite.de'},
    {"domain": 'vergabeplattform.stadt-koeln.de', "site_url": 'https://vergabeplattform.stadt-koeln.de'},
    {"domain": 'vergabeportal-bw.de', "site_url": 'https://vergabeportal-bw.de'},
    {"domain": 'www.acingov.pt', "site_url": 'https://www.acingov.pt'},
    {"domain": 'www.ausschreibung.swh.de', "site_url": 'https://www.ausschreibung.swh.de'},
    {"domain": 'www.ausschreibungen.ls.brandenburg.de', "site_url": 'https://www.ausschreibungen.ls.brandenburg.de'},
    {"domain": 'www.bundespolizei.de', "site_url": 'http://www.bundespolizei.de'},
    {"domain": 'www.deutsche-evergabe.de', "site_url": 'http://www.deutsche-evergabe.de'},
    {"domain": 'www.deutsche-rentenversicherung-bund.de', "site_url": 'https://www.deutsche-rentenversicherung-bund.de'},
    {"domain": 'www.deutsches-ausschreibungsblatt.de', "site_url": 'https://www.deutsches-ausschreibungsblatt.de'},
    {"domain": 'www.dtvp.de', "site_url": 'https://www.dtvp.de'},
    {"domain": 'www.enarocanje.si', "site_url": 'https://www.enarocanje.si'},
    {"domain": 'www.evergabe-online.de', "site_url": 'https://www.evergabe-online.de'},
    {"domain": 'www.evergabe.bayern.de', "site_url": 'https://www.evergabe.bayern.de'},
    {"domain": 'www.evergabe.de', "site_url": 'https://www.evergabe.de'},
    {"domain": 'www.evergabe.nrw.de', "site_url": 'https://www.evergabe.nrw.de'},
    {"domain": 'www.evergabe.sachsen.de', "site_url": 'https://www.evergabe.sachsen.de'},
    {"domain": 'www.had.de', "site_url": 'https://www.had.de'},
    {"domain": 'www.iss-ffm.de', "site_url": 'https://www.iss-ffm.de'},
    {"domain": 'www.kvb.de', "site_url": 'https://www.kvb.de'},
    {"domain": 'www.laenderfinanzierungsprogramm.de', "site_url": 'https://www.laenderfinanzierungsprogramm.de'},
    {"domain": 'www.lubey.de', "site_url": 'https://www.lubey.de'},
    {"domain": 'www.lwl.org', "site_url": 'https://www.lwl.org'},
    {"domain": 'www.meinauftrag.rib.de', "site_url": 'https://www.meinauftrag.rib.de'},
    {"domain": 'www.sachsen-vergabe.de', "site_url": 'https://www.sachsen-vergabe.de'},
    {"domain": 'www.staatsanzeiger-eservices.de', "site_url": 'https://www.staatsanzeiger-eservices.de'},
    {"domain": 'www.subreport-elvis.de', "site_url": 'https://www.subreport-elvis.de'},
    {"domain": 'www.subreport.de', "site_url": 'https://www.subreport.de'},
    {"domain": 'www.tender24.de', "site_url": 'https://www.tender24.de'},
    {"domain": 'www.vea-ausschreibungen.de', "site_url": 'https://www.vea-ausschreibungen.de'},
    {"domain": 'www.vergabe-westfalen.de', "site_url": 'https://www.vergabe-westfalen.de'},
    {"domain": 'www.vergabe.bayern.de', "site_url": 'http://www.vergabe.bayern.de'},
    {"domain": 'www.vergabe.metropoleruhr.de', "site_url": 'https://www.vergabe.metropoleruhr.de'},
    {"domain": 'www.vergabe.rib.de', "site_url": 'https://www.vergabe.rib.de'},
    {"domain": 'www.vergabe.stadt-frankfurt.de', "site_url": 'http://www.vergabe.stadt-frankfurt.de'},
    {"domain": 'www.vergabe24.de', "site_url": 'https://www.vergabe24.de'},
    {"domain": 'www.vergabemarktplatz-mv.de', "site_url": 'https://www.vergabemarktplatz-mv.de'},
    {"domain": 'www.vergaben-wirtschaftsregion-aachen.de', "site_url": 'https://www.vergaben-wirtschaftsregion-aachen.de'},
    {"domain": 'www.vgem-mellingen.de', "site_url": 'http://www.vgem-mellingen.de'},
    {"domain": 'www.vmp-rheinland.de', "site_url": 'https://www.vmp-rheinland.de'},
    {"domain": 'www.volksbund.de', "site_url": 'https://www.volksbund.de'},
    {"domain": 'xvergabe.de', "site_url": 'https://xvergabe.de'},
]
