"""baseline_schema

Revision ID: 20197da623db
Revises: 
Create Date: 2026-06-05 14:04:08.673182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20197da623db'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('runtime_seconds', sa.Float(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('trace', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_agent_name'), 'agent_runs', ['agent_name'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('item_id', sa.String(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('strategy', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_job_id'), 'audit_logs', ['job_id'], unique=False)
    op.create_table('evaluation_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('expected_docs', sa.Integer(), nullable=False),
    sa.Column('downloaded_docs', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('iterations', sa.Integer(), nullable=False),
    sa.Column('runtime_seconds', sa.Float(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_runs_model'), 'evaluation_runs', ['model'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('submitted_by', sa.String(), nullable=True),
    sa.Column('total_urls', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scraper_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('route_used', sa.Boolean(), nullable=False),
    sa.Column('cua_hint', sa.Text(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('avg_runtime', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraper_templates_domain'), 'scraper_templates', ['domain'], unique=True)
    op.create_table('job_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('strategy', sa.String(), nullable=False),
    sa.Column('iterations', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('runtime_seconds', sa.Float(), nullable=False),
    sa.Column('failure_category', sa.String(), nullable=True),
    sa.Column('attempts_detail', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_items_domain'), 'job_items', ['domain'], unique=False)
    op.create_index(op.f('ix_job_items_failure_category'), 'job_items', ['failure_category'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_item_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('s3_key', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_item_id'], ['job_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extraction_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_item_id', sa.String(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('fields_json', sa.Text(), nullable=False),
    sa.Column('docs_parsed', sa.Integer(), nullable=False),
    sa.Column('runtime_seconds', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_item_id'], ['job_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_records_job_item_id'), 'extraction_records', ['job_item_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extraction_records_job_item_id'), table_name='extraction_records')
    op.drop_table('extraction_records')
    op.drop_table('documents')
    op.drop_index(op.f('ix_job_items_failure_category'), table_name='job_items')
    op.drop_index(op.f('ix_job_items_domain'), table_name='job_items')
    op.drop_table('job_items')
    op.drop_index(op.f('ix_scraper_templates_domain'), table_name='scraper_templates')
    op.drop_table('scraper_templates')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_evaluation_runs_model'), table_name='evaluation_runs')
    op.drop_table('evaluation_runs')
    op.drop_index(op.f('ix_audit_logs_job_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_agent_runs_agent_name'), table_name='agent_runs')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
